const articulosZapatillas = [
  {
    id: 1,
    nombre: "Zapatillas Puma Comet 2 Alt Beta ADP de Mujer",
    marca: "Puma",
    categoria: "Mujer",
    imagen: "./img/articulos/Zapatillas Puma Comet 2 Alt Beta ADP de Mujer.jpg",
    precio: 1000,
    oferta: true,
    favorito: false,
  },
  {
    id: 2,
    nombre: "Zapatillas adidas Coreracer De Mujer",
    marca: "Adidas",
    categoria: "Mujer",
    imagen: "./img/articles/Zapatillas adidas Coreracer De Mujer.jpg",
    precio: 2000,
    oferta: true,
    favorito: false,
  },
  {
    id: 3,
    nombre: "Zapatillas Puma Flyer Flex De Hombre",
    marca: "Puma",
    categoria: "Hombre",
    imagen: "./img/articles/Zapatillas Puma Flyer Flex De Hombre.jpg",
    precio: 1000,
    oferta: true,
    favorito: false,
  },
  {
    id: 4,
    nombre: "Zapatillas adidas Fluidup De Hombre",
    marca: "Adidas",
    categoria: "Hombre",
    imagen: "./img/articles/Zapatillas adidas Fluidup De Hombre.jpg",
    precio: 2000,
    oferta: true,
    favorito: false,
  },
  {
    id: 5,
    nombre: "Zapatillas adidas Grand Court Minnie Mouse Niños",
    marca: "Adidas",
    categoria: "Niño",
    imagen:
      "./img/articles/Zapatillas adidas Grand Court Minnie Mouse  Niños.jpg",
    precio: 1000,
    oferta: true,
    favorito: false,
  },
  {
    id: 6,
    nombre: "Zapatillas adidas Tensaur Sport De Niños",
    marca: "Adidas",
    categoria: "Niño",
    imagen: "./img/articles/Zapatillas adidas Tensaur Sport De Niños.jpg",
    precio: 2000,
    oferta: true,
    favorito: false,
  },
];
