const articulosZapatillas = [
  {
    id: 1,
    nombre: "Zapatillas Adidas Coreracer De Mujer",
    marca: "Adidas",
    categoria: "Mujer",
    imagen: "./multimedia/articulos/ZapatillasAdidasCoreracerDeMujer.jpg",
    precio: 1000,
    cantidad: 1,
    oferta: true,
    favorito: false,
  },
  {
    id: 2,
    nombre: "Zapatillas Puma Comet 2 Alt Beta ADP de Mujer",
    marca: "Puma",
    categoria: "Mujer",
    imagen: "./multimedia/articulos/ZapatillasPumaComet2AltBetaADPMujer.jpg",
    precio: 2000,
    cantidad: 1,
    oferta: false,
    favorito: false,
  },
  {
    id: 3,
    nombre: "Zapatillas adidas Fluidup De Hombre",
    marca: "Adidas",
    categoria: "Hombre",
    imagen: "./multimedia/articulos/ZapatillasAdidasFluidupDeHombre.jpg",
    precio: 1000,
    cantidad: 1,
    oferta: true,
    favorito: false,
  },
  {
    id: 4,
    nombre: "Zapatillas Puma Flyer Flex De Hombre",
    marca: "Puma",
    categoria: "Hombre",
    imagen: "./multimedia/articulos/ZapatillasPumaFlyerFlexDeHombre.jpg",
    precio: 2000,
    cantidad: 1,
    oferta: false,
    favorito: false,
  },
  {
    id: 5,
    nombre: "Zapatillas adidas Grand Court Minnie Mouse Niños",
    marca: "Adidas",
    categoria: "Niño",
    imagen:"./multimedia/articulos/ZapatillasAdidasGrandCourtMinnieMouseNiños.jpg",
    precio: 1000,
    cantidad: 1,
    oferta: true,
    favorito: false,
  },
  {
    id: 6,
    nombre: "Zapatillas adidas Tensaur Sport De Niños",
    marca: "Adidas",
    categoria: "Niño",
    imagen: "./multimedia/articulos/ZapatillasAdidasTensaurSportDeNiños.jpg",
    precio: 2000,
    cantidad: 1,
    oferta: false,
    favorito: false,
  },
  {
    id: 7,
    nombre: "Zapatillas Olimpikus Barra Unisex",
    marca: "Olympikus",
    categoria: "Unisex",
    imagen: "./multimedia/articulos/ZapatillasOlympikusBarraUnisex.jpg",
    precio: 3000,
    cantidad: 1,
    oferta: false,
    favorito: false,
  },
  {
    id: 8,
    nombre: "Zapatillas Under Armour Assert 9 Ac De Niños",
    marca: "Under Armour Assert 9 Ac",
    categoria: "Niño",
    imagen: "./multimedia/articulos/ZapatillasUnderArmourAssert9AcDeNiños.jpg",
    precio: 1500,
    cantidad: 1,
    oferta: false,
    favorito: false,
  },
  {
    id: 9,
    nombre: "Zapatillas Kappa Porto De Niñas",
    marca: "Kappa Porto",
    categoria: "Niña",
    imagen: "./multimedia/articulos/ZapatillasKappaPortoDeNiñas.jpg",
    precio: 2000,
    cantidad: 1,
    oferta: true,
    favorito: false,
  },
  {
    id: 10,
    nombre: "Zapatillas Adidas Showtheway De Mujer",
    marca: "Adidas Showtheway",
    categoria: "Mujer",
    imagen: "./multimedia/articulos/ZapatillasadidasShowthewayDeMujer.jpg",
    precio: 3000,
    cantidad: 1,
    oferta: false,
    favorito: false,
  },
  {
    id: 11,
    nombre: "Zapatilla Shimano TR501 De Mujer",
    marca: "Shimano TR501",
    categoria: "Mujer",
    imagen: "./multimedia/articulos/ZapatillaShimanoTR501DeMujer.jpg",
    precio: 2000,
    cantidad: 1,
    oferta: true,
    favorito:false,
  },
  {
    id: 12,
    nombre: "Zapatillas Puma Comet 2 Alt Beta De Hombre",
    marca: "Puma Comet 2 Alt Beta",
    categoria: "Hombre",
    imagen: "./multimedia/articulos/ZapatillasPumaComet2AltBetaDeHombre.jpeg",
    precio: 4000,
    cantidad: 1,
    oferta: false,
    favorito: false,
  },
  {
    id: 13,
    nombre: "Zapatillas Reebok Classic Leather De Mujer",
    marca: "Reebok Classic Leather",
    categoria: "Mujer",
    imagen: "./multimedia/articulos/ZapatillasReebokClassicLeatherDeMujer.jpg",
    precio: 5000,
    cantidad: 1,
    oferta: true,
    favorito: false,
  },
  {
    id: 14,
    nombre: "Zapatillas Puma Flyer Flex Adiprene De Hombre",
    marca: "Puma Flyer Flex Adiprene",
    categoria: "Hombre",
    imagen: "./multimedia/articulos/ZapatillasPumaFlyerFlexAdipreneDeHombre.jpg",
    precio: 4000,
    cantidad: 1,
    oferta: false,
    favorito: false,
  },
  {
    id: 15,
    nombre: "Zapatillas Fila Recovery De Niños",
    marca: "Fila Recovery",
    categoria: "Niños",
    imagen: "./multimedia/articulos/ZapatillasFilaRecoveryDeNiños.jpg",
    precio: 2000,
    cantidad: 1,
    oferta: false,
    favorito: false,
  },
];
