const articulosZapatillas = [
  {
    id: 1,
    nombre: "Zapatillas Puma Comet 2 Alt Beta ADP de Mujer",
    marca: "Puma",
    categoria: "Mujer",
    imagen: "./multimedia/articulos/ZapatillasAdidasCoreracerDeMujer.jpg",
    precio: 1000,
    cantidad: 1,
    oferta: true,
    favorito: false,
  },
  {
    id: 2,
    nombre: "Zapatillas Adidas Coreracer De Mujer",
    marca: "Adidas",
    categoria: "Mujer",
    imagen: "./multimedia/articulos/ZapatillasPumaComet2AltBetaADPMujer.jpg",
    precio: 2000,
    cantidad: 1,
    oferta: false,
    favorito: false,
  },
  {
    id: 3,
    nombre: "Zapatillas Puma Flyer Flex De Hombre",
    marca: "Puma",
    categoria: "Hombre",
    imagen: "./multimedia/articulos/ZapatillasAdidasFluidupDeHombre.jpg",
    precio: 1000,
    cantidad: 1,
    oferta: true,
    favorito: false,
  },
  {
    id: 4,
    nombre: "Zapatillas adidas Fluidup De Hombre",
    marca: "Adidas",
    categoria: "Hombre",
    imagen: "./multimedia/articulos/ZapatillasPumaFlyerFlexDeHombre.jpg",
    precio: 2000,
    cantidad: 1,
    oferta: false,
    favorito: false,
  },
  {
    id: 5,
    nombre: "Zapatillas adidas Grand Court Minnie Mouse Niños",
    marca: "Adidas",
    categoria: "Niño",
    imagen:"./multimedia/articulos/ZapatillasAdidasGrandCourtMinnieMouseNiños.jpg",
    precio: 1000,
    cantidad: 1,
    oferta: true,
    favorito: false,
  },
  {
    id: 6,
    nombre: "Zapatillas adidas Tensaur Sport De Niños",
    marca: "Adidas",
    categoria: "Niño",
    imagen: "./multimedia/articulos/ZapatillasAdidasTensaurSportDeNiños.jpg",
    precio: 2000,
    cantidad: 1,
    oferta: false,
    favorito: false,
  },
];
